//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "purchase_attribute")]
pub enum PurchaseAttribute {
    #[sea_orm(string_value = "convenience_store")]
    ConvenienceStore,
    #[sea_orm(string_value = "grocery_store")]
    GroceryStore,
    #[sea_orm(string_value = "hardware_store")]
    HardwareStore,
    #[sea_orm(string_value = "pharmacy")]
    Pharmacy,
    #[sea_orm(string_value = "supermarket")]
    Supermarket,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "role")]
pub enum Role {
    #[sea_orm(string_value = "admin")]
    Admin,
    #[sea_orm(string_value = "member")]
    Member,
}
